name: Daily Commit

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config --global user.name "Shawnn Ongyiu"
          git config --global user.email "shawnnongyiu@gmail.com"

      - name: Make daily commit
        run: |
          echo "Last run: $(date -u)" > last-updated.txt
          git add last-updated.txt
          git commit -m "Daily update: $(date -u '+%Y-%m-%d')" || echo "No changes to commit"

      - name: Push changes using GITHUB_TOKEN
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push
